# 线上配置文件
server:
  port: 8000
spring:
  # MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.76.40:3306/pim
    username: root
    password: ZAQ1@wsx
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''

justauth:
  enabled: true
  type:
    GITEE:
      client-id: 797c9a935e1a4835ab993e4c4e4d50d95134353728aa958353947e9609069b82
      client-secret: 568d59b8d1dadf8aece963c8e29e1675056bd26dc0278d2c932d3e6f3e56fb19
      redirect-uri: https://api.pimonitor.top/gitee/callback
    GITHUB:
      client-id: Ov23li73rcZBXhnCoRoI
      client-secret: e3753067c245b0dcfd28a242078b9407d87552af
      redirect-uri: https://api.pimonitor.top/github/callback
    WECHAT_OPEN:
      client-id: wxcda274a39902039c
      client-secret: 0867d7b9a2b9e2b1d953adae1322f7e5
      redirect-uri: https://api.pimonitor.top/wechat_open/callback